repos:
  - repo: local
    hooks:
      - id: whitespace
        name: strip whitespace
        entry: find tinygrad -type f -name "*.py" -exec sed -i '' 's/ *$//' '{}' ';'
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry:
           mypy tinygrad/ test/ 
            --exclude=test/models/ 
            --exclude=test/unit/ 
            --exclude=test/web/ 
            --exclude=test/external/
            --exclude=test/imported/
            --exclude=test/testextra/
            --exclude=examples/
            --exclude=test/test_linearizer.py
            --exclude=test/test_linearizer_failures.py
            --exclude=test/test_search.py
            --exclude=test/test_tensor.py
            --exclude=test/test_multitensor.py
            --exclude=test/test_real_world.py
            --exclude=test/test_fuzz_shape_ops.py
            --exclude=test/test_hcq.py
            --exclude=test/test_nn.py
            --exclude=test/test_ops.py
            --exclude=test/test_schedule.py
            --exclude=test/test_pattern_matcher.py
            --exclude=test/test_optim.py
            --exclude=test/test_uops.py
            --exclude=test/test_optim.py
            --exclude=test/test_fusion_op.py
            --exclude=test/test_schedule.py
            --exclude=test/test_speed_v_torch.py
            --exclude=test/test_net_speed.py
            --exclude=test/test_method_cache.py
            --exclude=test/test_assign.py
            --exclude=test/test_device_speed.py
            --exclude=test/test_image_dtype.py
            --exclude=test/test_symbolic_shapetracker.py
            --exclude=test/test_symbolic_ops.py
            --exclude=test/test_graph.py
            --exclude=test/test_winograd.py
            --exclude=test/test_uops_stats.py
            --exclude=test/test_zero_copy.py
            --exclude=test/test_dtype_alu.py
            --exclude=test/test_lazyop.py
            --exclude=test/test_lazybuffer.py
            --exclude=test/test_transcendental.py
            --exclude=test/test_jit.py
            --exclude=test/test_const_folding.py
            --exclude=test/test_tensor_data.py
            --exclude=test/test_pickle.py
            --exclude=test/test_setitem.py
            --exclude=test/test_kernel_cache.py
            --exclude=test/test_randomness.py
        language: system
        always_run: true
        pass_filenames: false
      - id: docs2
        name: docs2
        entry: python3 docs/abstractions2.py
        language: system
        always_run: true
        pass_filenames: false
      - id: devicetests
        name: select GPU tests
        entry: env GPU=1 PYTHONPATH="." pytest test/test_uops.py test/test_custom_function.py test/test_search.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of tests
        entry: env PYTHONPATH="." python3 -m pytest -n=4 test/unit/ test/test_ops.py test/test_dtype.py test/test_schedule.py test/test_custom_function.py test/test_assign.py test/test_symbolic_shapetracker.py
        language: system
        always_run: true
        pass_filenames: false
      - id: example
        name: multi device tests
        entry: python3 test/external/external_test_example.py
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: env PYTHONPATH="." python3 -m pylint tinygrad/
        language: system
        always_run: true
        pass_filenames: false