repos:
  - repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
  - repo: local
    hooks:
      - id: whitespace
        name: strip whitespace
        entry: .pre-commit-hooks-scripts/strip_whitespace.sh
        language: system
        always_run: true
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff . --preview
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy tinygrad/
        language: system
        always_run: true
        pass_filenames: false
      - id: linecount
        name: Repo line count
        entry: python3 ./sz.py
        language: system
        always_run: true
      - id: sloccount
        name: Check <5000 lines
        entry: .pre-commit-hooks-scripts/check_lines.sh
        language: system
        always_run: true
      - id: testquickstart
        name: Test Quickstart
        entry: .pre-commit-hooks-scripts/test_quickstart.sh 
        language: system
        always_run: true
      - id: fuzztestsymbolic
        name: Fuzz Test symbolic
        entry: python3 test/external/fuzz_symbolic.py
        language: system
        always_run: true
      - id: fuzztestshapetracker
        name: Fuzz Test shapetracker
        entry: env PYTHONPATH="." python3 test/external/fuzz_shapetracker.py
        language: system
        always_run: true
      - id: testshapetrackertomovementops
        name: Test shapetracker to_movement_ops
        entry: python3 extra/to_movement_ops.py
        language: system
        always_run: true
      - id: useasexternalpackage
        name: Use as an external package
        entry: .pre-commit-hooks-scripts/use_as_external_package.sh
        language: system
        always_run: true
      - id: docs
        name: docs
        entry: |
          python3 docs/abstractions.py
          python3 docs/beautiful.py
        language: system
        always_run: true
        pass_filenames: false
      - id: devicetests
        name: select GPU tests
        entry: env GPU=1 PYTHONPATH="." pytest test/test_uops.py test/test_custom_function.py test/test_search.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of TORCH tests
        entry: env PYTHONPATH="." TORCH=1 python3 -m pytest -n=4 test/unit/ test/test_ops.py test/test_dtype.py test/test_schedule.py test/test_custom_function.py test/test_assign.py test/test_symbolic_shapetracker.py
        language: system
        always_run: true
        pass_filenames: false
      - id: example
        name: multi device tests
        entry: python3 test/external/external_test_example.py
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: env PYTHONPATH="." python3 -m pylint tinygrad/
        language: system
        always_run: true
        pass_filenames: false
