[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tinygrad"
authors = [{ name = "George Hotz" }]
version = "0.7.0"
description = "You like pytorch? You like micrograd? You love tinygrad! <3"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy",
    "requests",
    "tqdm",
    "networkx",
    "pyopencl",
    "pyobjc-framework-Metal; platform_system=='Darwin'",
    "pyobjc-framework-Cocoa; platform_system=='Darwin'",
    "pyobjc-framework-libdispatch; platform_system=='Darwin'",
]
requires-python = ">=3.8"

[tool.setuptools]
packages = [
    "tinygrad",
    "tinygrad.codegen",
    "tinygrad.nn",
    "tinygrad.renderer",
    "tinygrad.runtime",
    "tinygrad.shape",
    "tinygrad.features",
]

[project.optional-dependencies]
triton = ["triton-nightly>=2.1.0.dev20231014192330", "pycuda"]
llvm = ["llvmlite"]
cuda = ["pycuda"]
arm = ["unicorn"]
webgpu = ["wgpu"]
linting = [
    "flake8",
    "pylint",
    "mypy",
    "typing-extensions",
    "pre-commit",
    "ruff",
    "types-tqdm",
]
testing = [
    "torch",
    "pillow",
    "pytest",
    "pytest-xdist",
    "onnx==1.15.0",
    "onnx2torch",
    "opencv-python",
    "tabulate",
    "safetensors",
    "cloudpickle",
    "transformers",
    "sentencepiece",
    "tiktoken",
    "librosa",
]