name: "Tinygrad Size Guarantee"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y cargo
    - run: cargo install tokei
    - run: tokei . --output json
    
