name: "Tinygrad Size Guarantee"
on:
  pull_request:
  push:
strategy:
  max-parallel: 2
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: npm install sloc
    - run: test $(sloc **/*.py | grep -i "source" | cut -d ":" -f 2 | xargs) -le 1000
