name: cuda manual test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run_nv_tests:
    name: nv tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Cache python packages
      uses: actions/cache@v3
      with:
        path: ${{ env.Python3_ROOT_DIR }}/lib/python3.8/site-packages
        key: linting-packages-${{ hashFiles('**/setup.py') }}-3.8
    - name: Install dependencies
      run: pip install -e '.[linting,testing]' --extra-index-url https://download.pytorch.org/whl/cpu
    - name: get nvidia semi specs
      run: nvidia-smi
    - name: driver
      run: nvcc --version
    - name: run script
      run: python ./nv.py
